# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calib_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lib_param.proto\x12\x07minieye\"\xc1\x02\n\nCalibParam\x12\x14\n\x0c\x63\x61mera_pitch\x18\x01 \x01(\x01\x12\x12\n\ncamera_yaw\x18\x02 \x01(\x01\x12\x13\n\x0b\x63\x61mera_roll\x18\x03 \x01(\x01\x12\x11\n\tcamera_cu\x18\x04 \x01(\x01\x12\x11\n\tcamera_cv\x18\x05 \x01(\x01\x12\x14\n\x0c\x63\x61mera_fov_h\x18\x06 \x01(\x01\x12\x14\n\x0c\x63\x61mera_fov_w\x18\x07 \x01(\x01\x12\x15\n\rcamera_height\x18\x08 \x01(\x01\x12\x1b\n\x13left_dist_to_camera\x18\t \x01(\x01\x12\x1c\n\x14right_dist_to_camera\x18\n \x01(\x01\x12\x1c\n\x14\x66ront_dist_to_camera\x18\x0b \x01(\x01\x12\x1f\n\x17\x66ront_wheel_camera_dist\x18\x0c \x01(\x01\x12\x11\n\tcamera_id\x18\r \x01(\rb\x06proto3')



_CALIBPARAM = DESCRIPTOR.message_types_by_name['CalibParam']
CalibParam = _reflection.GeneratedProtocolMessageType('CalibParam', (_message.Message,), {
  'DESCRIPTOR' : _CALIBPARAM,
  '__module__' : 'calib_param_pb2'
  # @@protoc_insertion_point(class_scope:minieye.CalibParam)
  })
_sym_db.RegisterMessage(CalibParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALIBPARAM._serialized_start=31
  _CALIBPARAM._serialized_end=352
# @@protoc_insertion_point(module_scope)
