# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_occlusion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61mera_occlusion.proto\x12\nperception\"c\n\x0f\x43\x61meraOcclusion\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x11\n\tcamera_id\x18\x03 \x01(\x05\x12\x18\n\x10\x63\x61mera_occlusion\x18\x04 \x01(\x05\x62\x06proto3')



_CAMERAOCCLUSION = DESCRIPTOR.message_types_by_name['CameraOcclusion']
CameraOcclusion = _reflection.GeneratedProtocolMessageType('CameraOcclusion', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAOCCLUSION,
  '__module__' : 'camera_occlusion_pb2'
  # @@protoc_insertion_point(class_scope:perception.CameraOcclusion)
  })
_sym_db.RegisterMessage(CameraOcclusion)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAOCCLUSION._serialized_start=38
  _CAMERAOCCLUSION._serialized_end=137
# @@protoc_insertion_point(module_scope)
