# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_header.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_header.proto\x12\x07minieye\"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\r\x12\x0c\n\x04nsec\x18\x02 \x01(\r\"f\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12 \n\ttimestamp\x18\x03 \x01(\x0b\x32\r.minieye.Time\x12\x1b\n\x04tick\x18\x04 \x01(\x0b\x32\r.minieye.Timeb\x06proto3')



_TIME = DESCRIPTOR.message_types_by_name['Time']
_HEADER = DESCRIPTOR.message_types_by_name['Header']
Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'data_header_pb2'
  # @@protoc_insertion_point(class_scope:minieye.Time)
  })
_sym_db.RegisterMessage(Time)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'data_header_pb2'
  # @@protoc_insertion_point(class_scope:minieye.Header)
  })
_sym_db.RegisterMessage(Header)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=30
  _TIME._serialized_end=63
  _HEADER._serialized_start=65
  _HEADER._serialized_end=167
# @@protoc_insertion_point(module_scope)
