# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_source.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_source.proto\x12\x07minieye*G\n\nDataSource\x12\x0c\n\x08kMinieye\x10\x00\x12\n\n\x06kEyeQ3\x10\x01\x12\n\n\x06kEyeQ4\x10\x02\x12\x07\n\x03kJ2\x10\x03\x12\n\n\x06kLidar\x10\x04\x62\x06proto3')

_DATASOURCE = DESCRIPTOR.enum_types_by_name['DataSource']
DataSource = enum_type_wrapper.EnumTypeWrapper(_DATASOURCE)
kMinieye = 0
kEyeQ3 = 1
kEyeQ4 = 2
kJ2 = 3
kLidar = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASOURCE._serialized_start=30
  _DATASOURCE._serialized_end=101
# @@protoc_insertion_point(module_scope)
