# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pyproto.geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dev_object.proto',
  package='perception',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x65v_object.proto\x12\nperception\x1a\x0egeometry.proto\"\xc2\x05\n\rDevObjectList\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttick_time\x18\x02 \x01(\x04\x12\x13\n\x0bsteady_time\x18\x03 \x01(\x04\x12:\n\talgo_type\x18\x05 \x01(\x0e\x32\'.perception.DevObjectList.AlgorithmType\x12\x11\n\ttime_list\x18\x06 \x03(\x04\x12\x30\n\x03\x64\x65t\x18\n \x01(\x0b\x32#.perception.DevObjectList.Detection\x12\x33\n\x04pose\x18\x0b \x01(\x0b\x32%.perception.DevObjectList.VehiclePose\x12\x38\n\x07\x63ls_reg\x18\x0c \x01(\x0b\x32\'.perception.DevObjectList.VehicleClsReg\x12\x35\n\x05track\x18\r \x01(\x0b\x32&.perception.DevObjectList.VehicleTrack\x1ao\n\tDetection\x12\x30\n\rraw_rect_list\x18\x01 \x03(\x0b\x32\x19.perception.common.Rect2f\x12\x30\n\rroi_rect_list\x18\x02 \x03(\x0b\x32\x19.perception.common.Rect2f\x1a\x1b\n\x0bVehiclePose\x12\x0c\n\x04pose\x18\x01 \x01(\x05\x1a<\n\rVehicleClsReg\x12+\n\x07pt_list\x18\x01 \x03(\x0b\x32\x1a.perception.common.Point2f\x1a<\n\x0cVehicleTrack\x12,\n\trect_list\x18\x01 \x03(\x0b\x32\x19.perception.common.Rect2f\"F\n\rAlgorithmType\x12\t\n\x05kNone\x10\x00\x12\x0b\n\x07kCommon\x10\x01\x12\x0c\n\x08kVehicle\x10\x02\x12\x0f\n\x0bkPedestrian\x10\x03\x62\x06proto3'
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])



_DEVOBJECTLIST_ALGORITHMTYPE = _descriptor.EnumDescriptor(
  name='AlgorithmType',
  full_name='perception.DevObjectList.AlgorithmType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kNone', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='kCommon', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='kVehicle', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='kPedestrian', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=685,
  serialized_end=755,
)
_sym_db.RegisterEnumDescriptor(_DEVOBJECTLIST_ALGORITHMTYPE)


_DEVOBJECTLIST_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='perception.DevObjectList.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_rect_list', full_name='perception.DevObjectList.Detection.raw_rect_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roi_rect_list', full_name='perception.DevObjectList.Detection.roi_rect_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=530,
)

_DEVOBJECTLIST_VEHICLEPOSE = _descriptor.Descriptor(
  name='VehiclePose',
  full_name='perception.DevObjectList.VehiclePose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='perception.DevObjectList.VehiclePose.pose', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=559,
)

_DEVOBJECTLIST_VEHICLECLSREG = _descriptor.Descriptor(
  name='VehicleClsReg',
  full_name='perception.DevObjectList.VehicleClsReg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pt_list', full_name='perception.DevObjectList.VehicleClsReg.pt_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=621,
)

_DEVOBJECTLIST_VEHICLETRACK = _descriptor.Descriptor(
  name='VehicleTrack',
  full_name='perception.DevObjectList.VehicleTrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rect_list', full_name='perception.DevObjectList.VehicleTrack.rect_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=683,
)

_DEVOBJECTLIST = _descriptor.Descriptor(
  name='DevObjectList',
  full_name='perception.DevObjectList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='perception.DevObjectList.frame_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tick_time', full_name='perception.DevObjectList.tick_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steady_time', full_name='perception.DevObjectList.steady_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algo_type', full_name='perception.DevObjectList.algo_type', index=3,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_list', full_name='perception.DevObjectList.time_list', index=4,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='det', full_name='perception.DevObjectList.det', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='perception.DevObjectList.pose', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cls_reg', full_name='perception.DevObjectList.cls_reg', index=7,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track', full_name='perception.DevObjectList.track', index=8,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVOBJECTLIST_DETECTION, _DEVOBJECTLIST_VEHICLEPOSE, _DEVOBJECTLIST_VEHICLECLSREG, _DEVOBJECTLIST_VEHICLETRACK, ],
  enum_types=[
    _DEVOBJECTLIST_ALGORITHMTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=755,
)

_DEVOBJECTLIST_DETECTION.fields_by_name['raw_rect_list'].message_type = geometry__pb2._RECT2F
_DEVOBJECTLIST_DETECTION.fields_by_name['roi_rect_list'].message_type = geometry__pb2._RECT2F
_DEVOBJECTLIST_DETECTION.containing_type = _DEVOBJECTLIST
_DEVOBJECTLIST_VEHICLEPOSE.containing_type = _DEVOBJECTLIST
_DEVOBJECTLIST_VEHICLECLSREG.fields_by_name['pt_list'].message_type = geometry__pb2._POINT2F
_DEVOBJECTLIST_VEHICLECLSREG.containing_type = _DEVOBJECTLIST
_DEVOBJECTLIST_VEHICLETRACK.fields_by_name['rect_list'].message_type = geometry__pb2._RECT2F
_DEVOBJECTLIST_VEHICLETRACK.containing_type = _DEVOBJECTLIST
_DEVOBJECTLIST.fields_by_name['algo_type'].enum_type = _DEVOBJECTLIST_ALGORITHMTYPE
_DEVOBJECTLIST.fields_by_name['det'].message_type = _DEVOBJECTLIST_DETECTION
_DEVOBJECTLIST.fields_by_name['pose'].message_type = _DEVOBJECTLIST_VEHICLEPOSE
_DEVOBJECTLIST.fields_by_name['cls_reg'].message_type = _DEVOBJECTLIST_VEHICLECLSREG
_DEVOBJECTLIST.fields_by_name['track'].message_type = _DEVOBJECTLIST_VEHICLETRACK
_DEVOBJECTLIST_ALGORITHMTYPE.containing_type = _DEVOBJECTLIST
DESCRIPTOR.message_types_by_name['DevObjectList'] = _DEVOBJECTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DevObjectList = _reflection.GeneratedProtocolMessageType('DevObjectList', (_message.Message,), {

  'Detection' : _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
    'DESCRIPTOR' : _DEVOBJECTLIST_DETECTION,
    '__module__' : 'dev_object_pb2'
    # @@protoc_insertion_point(class_scope:perception.DevObjectList.Detection)
    })
  ,

  'VehiclePose' : _reflection.GeneratedProtocolMessageType('VehiclePose', (_message.Message,), {
    'DESCRIPTOR' : _DEVOBJECTLIST_VEHICLEPOSE,
    '__module__' : 'dev_object_pb2'
    # @@protoc_insertion_point(class_scope:perception.DevObjectList.VehiclePose)
    })
  ,

  'VehicleClsReg' : _reflection.GeneratedProtocolMessageType('VehicleClsReg', (_message.Message,), {
    'DESCRIPTOR' : _DEVOBJECTLIST_VEHICLECLSREG,
    '__module__' : 'dev_object_pb2'
    # @@protoc_insertion_point(class_scope:perception.DevObjectList.VehicleClsReg)
    })
  ,

  'VehicleTrack' : _reflection.GeneratedProtocolMessageType('VehicleTrack', (_message.Message,), {
    'DESCRIPTOR' : _DEVOBJECTLIST_VEHICLETRACK,
    '__module__' : 'dev_object_pb2'
    # @@protoc_insertion_point(class_scope:perception.DevObjectList.VehicleTrack)
    })
  ,
  'DESCRIPTOR' : _DEVOBJECTLIST,
  '__module__' : 'dev_object_pb2'
  # @@protoc_insertion_point(class_scope:perception.DevObjectList)
  })
_sym_db.RegisterMessage(DevObjectList)
_sym_db.RegisterMessage(DevObjectList.Detection)
_sym_db.RegisterMessage(DevObjectList.VehiclePose)
_sym_db.RegisterMessage(DevObjectList.VehicleClsReg)
_sym_db.RegisterMessage(DevObjectList.VehicleTrack)


# @@protoc_insertion_point(module_scope)
