# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dvr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdvr.proto\x12\x07minieye\"\xa5\x02\n\tDvrSignal\x12:\n\x10\x66loat_value_list\x18\x01 \x03(\x0b\x32 .minieye.DvrSignal.FloatKeyValue\x12<\n\x11\x64ouble_value_list\x18\x02 \x03(\x0b\x32!.minieye.DvrSignal.DoubleKeyValue\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0c\n\x04tick\x18\x04 \x01(\x04\x1a=\n\rFloatKeyValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x0f\n\x07\x64\x65scrip\x18\x03 \x01(\t\x1a>\n\x0e\x44oubleKeyValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0f\n\x07\x64\x65scrip\x18\x03 \x01(\tb\x06proto3')



_DVRSIGNAL = DESCRIPTOR.message_types_by_name['DvrSignal']
_DVRSIGNAL_FLOATKEYVALUE = _DVRSIGNAL.nested_types_by_name['FloatKeyValue']
_DVRSIGNAL_DOUBLEKEYVALUE = _DVRSIGNAL.nested_types_by_name['DoubleKeyValue']
DvrSignal = _reflection.GeneratedProtocolMessageType('DvrSignal', (_message.Message,), {

  'FloatKeyValue' : _reflection.GeneratedProtocolMessageType('FloatKeyValue', (_message.Message,), {
    'DESCRIPTOR' : _DVRSIGNAL_FLOATKEYVALUE,
    '__module__' : 'dvr_pb2'
    # @@protoc_insertion_point(class_scope:minieye.DvrSignal.FloatKeyValue)
    })
  ,

  'DoubleKeyValue' : _reflection.GeneratedProtocolMessageType('DoubleKeyValue', (_message.Message,), {
    'DESCRIPTOR' : _DVRSIGNAL_DOUBLEKEYVALUE,
    '__module__' : 'dvr_pb2'
    # @@protoc_insertion_point(class_scope:minieye.DvrSignal.DoubleKeyValue)
    })
  ,
  'DESCRIPTOR' : _DVRSIGNAL,
  '__module__' : 'dvr_pb2'
  # @@protoc_insertion_point(class_scope:minieye.DvrSignal)
  })
_sym_db.RegisterMessage(DvrSignal)
_sym_db.RegisterMessage(DvrSignal.FloatKeyValue)
_sym_db.RegisterMessage(DvrSignal.DoubleKeyValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DVRSIGNAL._serialized_start=23
  _DVRSIGNAL._serialized_end=316
  _DVRSIGNAL_FLOATKEYVALUE._serialized_start=191
  _DVRSIGNAL_FLOATKEYVALUE._serialized_end=252
  _DVRSIGNAL_DOUBLEKEYVALUE._serialized_start=254
  _DVRSIGNAL_DOUBLEKEYVALUE._serialized_end=316
# @@protoc_insertion_point(module_scope)
