# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fail_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61il_detection.proto\x12\x07minieye\x1a\x0egeometry.proto\"\x9f\x02\n\x0fImageFailStatus\x12\x11\n\tfail_type\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05level\x18\x03 \x01(\x05\x12+\n\x07regions\x18\x04 \x03(\x0b\x32\x1a.perception.common.Polygon\"\\\n\x0cImgFailTypes\x12\x0e\n\nIMG_NORMAL\x10\x00\x12\x0c\n\x08IMG_BLUR\x10\x01\x12\x0f\n\x0bIMG_SHELTER\x10\x02\x12\x0e\n\nIMG_FREEZE\x10\x04\x12\r\n\tIMG_GLARE\x10\x08\"P\n\x0cImgFailLevel\x12\r\n\tFAIL_NONE\x10\x00\x12\r\n\tFAIL_MILD\x10\x01\x12\x11\n\rFAIL_MODERATE\x10\x02\x12\x0f\n\x0b\x46\x41IL_SEVERE\x10\x03\"\\\n\tImageFail\x12\x0e\n\x06\x63\x61m_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x05\x12-\n\x0b\x66\x61il_status\x18\x03 \x03(\x0b\x32\x18.minieye.ImageFailStatusb\x06proto3')



_IMAGEFAILSTATUS = DESCRIPTOR.message_types_by_name['ImageFailStatus']
_IMAGEFAIL = DESCRIPTOR.message_types_by_name['ImageFail']
_IMAGEFAILSTATUS_IMGFAILTYPES = _IMAGEFAILSTATUS.enum_types_by_name['ImgFailTypes']
_IMAGEFAILSTATUS_IMGFAILLEVEL = _IMAGEFAILSTATUS.enum_types_by_name['ImgFailLevel']
ImageFailStatus = _reflection.GeneratedProtocolMessageType('ImageFailStatus', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFAILSTATUS,
  '__module__' : 'fail_detection_pb2'
  # @@protoc_insertion_point(class_scope:minieye.ImageFailStatus)
  })
_sym_db.RegisterMessage(ImageFailStatus)

ImageFail = _reflection.GeneratedProtocolMessageType('ImageFail', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFAIL,
  '__module__' : 'fail_detection_pb2'
  # @@protoc_insertion_point(class_scope:minieye.ImageFail)
  })
_sym_db.RegisterMessage(ImageFail)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEFAILSTATUS._serialized_start=50
  _IMAGEFAILSTATUS._serialized_end=337
  _IMAGEFAILSTATUS_IMGFAILTYPES._serialized_start=163
  _IMAGEFAILSTATUS_IMGFAILTYPES._serialized_end=255
  _IMAGEFAILSTATUS_IMGFAILLEVEL._serialized_start=257
  _IMAGEFAILSTATUS_IMGFAILLEVEL._serialized_end=337
  _IMAGEFAIL._serialized_start=339
  _IMAGEFAIL._serialized_end=431
# @@protoc_insertion_point(module_scope)
