# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnsspos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgnsspos.proto\x12\x07minieye\"\xe5\x02\n\x0bGnssposData\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0c\n\x04tick\x18\x04 \x01(\x04\x12\x10\n\x08is_valid\x18\x05 \x01(\x08\x12\x10\n\x08gps_week\x18\x06 \x01(\r\x12\x0f\n\x07gps_sec\x18\x07 \x01(\x01\x12\x10\n\x08pos_type\x18\x08 \x01(\r\x12\x10\n\x08latitude\x18\t \x01(\x01\x12\x11\n\tlongitude\x18\n \x01(\x01\x12\x12\n\nundulation\x18\x0b \x01(\x02\x12\x0e\n\x06height\x18\x0c \x01(\x02\x12\x0f\n\x07lat_std\x18\r \x01(\x02\x12\x0f\n\x07lon_std\x18\x0e \x01(\x02\x12\x0f\n\x07hgt_std\x18\x0f \x01(\x02\x12\x0b\n\x03svs\x18\x10 \x01(\r\x12\x10\n\x08soln_svs\x18\x11 \x01(\r\x12\x10\n\x08\x64iff_age\x18\x12 \x01(\r\x12\x0c\n\x04hdop\x18\x13 \x01(\x02\x12\x0c\n\x04pdop\x18\x14 \x01(\x02\x12\x0c\n\x04tdop\x18\x15 \x01(\x02\x62\x06proto3')



_GNSSPOSDATA = DESCRIPTOR.message_types_by_name['GnssposData']
GnssposData = _reflection.GeneratedProtocolMessageType('GnssposData', (_message.Message,), {
  'DESCRIPTOR' : _GNSSPOSDATA,
  '__module__' : 'gnsspos_pb2'
  # @@protoc_insertion_point(class_scope:minieye.GnssposData)
  })
_sym_db.RegisterMessage(GnssposData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSSPOSDATA._serialized_start=27
  _GNSSPOSDATA._serialized_end=384
# @@protoc_insertion_point(module_scope)
