# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ihc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2
import data_source_pb2 as data__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tihc.proto\x12\nperception\x1a\x0egeometry.proto\x1a\x11\x64\x61ta_source.proto\"\xb9\x03\n\x03Ihc\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x33\n\nlight_list\x18\x03 \x03(\x0b\x32\x1f.perception.Ihc.IhcDetectObject\x12-\n\nihc_signal\x18\x04 \x01(\x0b\x32\x19.perception.Ihc.IhcSignal\x12(\n\x0b\x64\x61ta_source\x18\x05 \x01(\x0e\x32\x13.minieye.DataSource\x1a\x64\n\x0fIhcDetectObject\x12+\n\x08\x64\x65t_rect\x18\x01 \x01(\x0b\x32\x19.perception.common.Rect2f\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08hit_type\x18\x03 \x01(\x05\x1a\x42\n\tIhcSignal\x12\x35\n\x0e\x63ontrol_signal\x18\x01 \x01(\x0e\x32\x1d.perception.Ihc.IhcSignalType\"U\n\rIhcSignalType\x12\x11\n\rkLightInvalid\x10\x00\x12\r\n\tkLightOff\x10\x01\x12\x0f\n\x0bkHighBeamOn\x10\x02\x12\x11\n\rkDippedBeamOn\x10\x03\x62\x06proto3')



_IHC = DESCRIPTOR.message_types_by_name['Ihc']
_IHC_IHCDETECTOBJECT = _IHC.nested_types_by_name['IhcDetectObject']
_IHC_IHCSIGNAL = _IHC.nested_types_by_name['IhcSignal']
_IHC_IHCSIGNALTYPE = _IHC.enum_types_by_name['IhcSignalType']
Ihc = _reflection.GeneratedProtocolMessageType('Ihc', (_message.Message,), {

  'IhcDetectObject' : _reflection.GeneratedProtocolMessageType('IhcDetectObject', (_message.Message,), {
    'DESCRIPTOR' : _IHC_IHCDETECTOBJECT,
    '__module__' : 'ihc_pb2'
    # @@protoc_insertion_point(class_scope:perception.Ihc.IhcDetectObject)
    })
  ,

  'IhcSignal' : _reflection.GeneratedProtocolMessageType('IhcSignal', (_message.Message,), {
    'DESCRIPTOR' : _IHC_IHCSIGNAL,
    '__module__' : 'ihc_pb2'
    # @@protoc_insertion_point(class_scope:perception.Ihc.IhcSignal)
    })
  ,
  'DESCRIPTOR' : _IHC,
  '__module__' : 'ihc_pb2'
  # @@protoc_insertion_point(class_scope:perception.Ihc)
  })
_sym_db.RegisterMessage(Ihc)
_sym_db.RegisterMessage(Ihc.IhcDetectObject)
_sym_db.RegisterMessage(Ihc.IhcSignal)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IHC._serialized_start=61
  _IHC._serialized_end=502
  _IHC_IHCDETECTOBJECT._serialized_start=247
  _IHC_IHCDETECTOBJECT._serialized_end=347
  _IHC_IHCSIGNAL._serialized_start=349
  _IHC_IHCSIGNAL._serialized_end=415
  _IHC_IHCSIGNALTYPE._serialized_start=417
  _IHC_IHCSIGNALTYPE._serialized_end=502
# @@protoc_insertion_point(module_scope)
