# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_attribute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pyproto.geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_attribute.proto',
  package='perception',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16object_attribute.proto\x12\nperception\x1a\x0egeometry.proto\"\xf7\x02\n\x05\x42ox3D\x12,\n\x08lower_lt\x18\x01 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08lower_lb\x18\x02 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08lower_rb\x18\x03 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08lower_rt\x18\x04 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08upper_lt\x18\x05 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08upper_lb\x18\x06 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08upper_rb\x18\x07 \x01(\x0b\x32\x1a.perception.common.Point2f\x12,\n\x08upper_rt\x18\x08 \x01(\x0b\x32\x1a.perception.common.Point2f\"X\n\nBox3DGroup\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12%\n\nbox3d_list\x18\x03 \x03(\x0b\x32\x11.perception.Box3Db\x06proto3'
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])




_BOX3D = _descriptor.Descriptor(
  name='Box3D',
  full_name='perception.Box3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower_lt', full_name='perception.Box3D.lower_lt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_lb', full_name='perception.Box3D.lower_lb', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_rb', full_name='perception.Box3D.lower_rb', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_rt', full_name='perception.Box3D.lower_rt', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_lt', full_name='perception.Box3D.upper_lt', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_lb', full_name='perception.Box3D.upper_lb', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_rb', full_name='perception.Box3D.upper_rb', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_rt', full_name='perception.Box3D.upper_rt', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=430,
)


_BOX3DGROUP = _descriptor.Descriptor(
  name='Box3DGroup',
  full_name='perception.Box3DGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='perception.Box3DGroup.frame_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='perception.Box3DGroup.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box3d_list', full_name='perception.Box3DGroup.box3d_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=520,
)

_BOX3D.fields_by_name['lower_lt'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['lower_lb'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['lower_rb'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['lower_rt'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['upper_lt'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['upper_lb'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['upper_rb'].message_type = geometry__pb2._POINT2F
_BOX3D.fields_by_name['upper_rt'].message_type = geometry__pb2._POINT2F
_BOX3DGROUP.fields_by_name['box3d_list'].message_type = _BOX3D
DESCRIPTOR.message_types_by_name['Box3D'] = _BOX3D
DESCRIPTOR.message_types_by_name['Box3DGroup'] = _BOX3DGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Box3D = _reflection.GeneratedProtocolMessageType('Box3D', (_message.Message,), {
  'DESCRIPTOR' : _BOX3D,
  '__module__' : 'object_attribute_pb2'
  # @@protoc_insertion_point(class_scope:perception.Box3D)
  })
_sym_db.RegisterMessage(Box3D)

Box3DGroup = _reflection.GeneratedProtocolMessageType('Box3DGroup', (_message.Message,), {
  'DESCRIPTOR' : _BOX3DGROUP,
  '__module__' : 'object_attribute_pb2'
  # @@protoc_insertion_point(class_scope:perception.Box3DGroup)
  })
_sym_db.RegisterMessage(Box3DGroup)


# @@protoc_insertion_point(module_scope)
