# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedestrian.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pyproto.geometry_pb2 as geometry__pb2
import pyproto.data_source_pb2 as data__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pedestrian.proto\x12\nperception\x1a\x0egeometry.proto\x1a\x11\x64\x61ta_source.proto\"\xf3\x06\n\nPedestrian\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x35\n\x08ped_list\x18\x03 \x03(\x0b\x32#.perception.Pedestrian.PedDetExport\x12<\n\x0bped_warning\x18\x04 \x01(\x0b\x32\'.perception.Pedestrian.PedWarningExport\x12(\n\x0b\x64\x61ta_source\x18\x05 \x01(\x0e\x32\x13.minieye.DataSource\x1a\xec\x04\n\x0cPedDetExport\x12-\n\ndetect_box\x18\x01 \x01(\x0b\x32\x19.perception.common.Rect2f\x12*\n\x07reg_box\x18\x02 \x01(\x0b\x32\x19.perception.common.Rect2f\x12,\n\ttrack_box\x18\x03 \x01(\x0b\x32\x19.perception.common.Rect2f\x12+\n\x08\x62ike_box\x18\x04 \x01(\x0b\x32\x19.perception.common.Rect2f\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x15\n\rdetect_status\x18\x06 \x01(\x05\x12\x0c\n\x04t_id\x18\x07 \x01(\x05\x12\x11\n\tunique_id\x18\x08 \x01(\x05\x12\x0f\n\x07time_ms\x18\t \x01(\x03\x12\x11\n\tpredicted\x18\n \x01(\x08\x12\x0f\n\x07world_x\x18\x0b \x01(\x02\x12\x0f\n\x07world_y\x18\x0c \x01(\x02\x12\x11\n\tpos_angle\x18\r \x01(\x02\x12\r\n\x05ttc_m\x18\x0e \x01(\x02\x12\x0b\n\x03ttc\x18\x0f \x01(\x02\x12\x1d\n\x15longitudinal_velocity\x18\x10 \x01(\x02\x12\x18\n\x10lateral_velocity\x18\x11 \x01(\x02\x12\x0e\n\x06real_H\x18\x12 \x01(\x02\x12\x0e\n\x06real_W\x18\x13 \x01(\x02\x12\x1d\n\x15is_longitudinal_close\x18\x14 \x01(\x08\x12\x18\n\x10is_lateral_close\x18\x15 \x01(\x08\x12\x1d\n\x15is_measure_not_stable\x18\x16 \x01(\x08\x12\x11\n\thave_bike\x18\x17 \x01(\x08\x12\x0e\n\x06is_key\x18\x18 \x01(\x08\x12\x11\n\tis_danger\x18\x19 \x01(\x08\x1a\x32\n\x10PedWarningExport\x12\x0e\n\x06ped_on\x18\x01 \x01(\x08\x12\x0e\n\x06pcw_on\x18\x02 \x01(\x08\x62\x06proto3')



_PEDESTRIAN = DESCRIPTOR.message_types_by_name['Pedestrian']
_PEDESTRIAN_PEDDETEXPORT = _PEDESTRIAN.nested_types_by_name['PedDetExport']
_PEDESTRIAN_PEDWARNINGEXPORT = _PEDESTRIAN.nested_types_by_name['PedWarningExport']
Pedestrian = _reflection.GeneratedProtocolMessageType('Pedestrian', (_message.Message,), {

  'PedDetExport' : _reflection.GeneratedProtocolMessageType('PedDetExport', (_message.Message,), {
    'DESCRIPTOR' : _PEDESTRIAN_PEDDETEXPORT,
    '__module__' : 'pedestrian_pb2'
    # @@protoc_insertion_point(class_scope:perception.Pedestrian.PedDetExport)
    })
  ,

  'PedWarningExport' : _reflection.GeneratedProtocolMessageType('PedWarningExport', (_message.Message,), {
    'DESCRIPTOR' : _PEDESTRIAN_PEDWARNINGEXPORT,
    '__module__' : 'pedestrian_pb2'
    # @@protoc_insertion_point(class_scope:perception.Pedestrian.PedWarningExport)
    })
  ,
  'DESCRIPTOR' : _PEDESTRIAN,
  '__module__' : 'pedestrian_pb2'
  # @@protoc_insertion_point(class_scope:perception.Pedestrian)
  })
_sym_db.RegisterMessage(Pedestrian)
_sym_db.RegisterMessage(Pedestrian.PedDetExport)
_sym_db.RegisterMessage(Pedestrian.PedWarningExport)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEDESTRIAN._serialized_start=68
  _PEDESTRIAN._serialized_end=951
  _PEDESTRIAN_PEDDETEXPORT._serialized_start=279
  _PEDESTRIAN_PEDDETEXPORT._serialized_end=899
  _PEDESTRIAN_PEDWARNINGEXPORT._serialized_start=901
  _PEDESTRIAN_PEDWARNINGEXPORT._serialized_end=951
# @@protoc_insertion_point(module_scope)
