# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2
import data_source_pb2 as data__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttsr.proto\x12\nperception\x1a\x0egeometry.proto\x1a\x11\x64\x61ta_source.proto\"\x8b\x04\n\x03Tsr\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12-\n\x08tsr_list\x18\x03 \x03(\x0b\x32\x1b.perception.Tsr.TsrTraceRes\x12/\n\x0btsr_warning\x18\x04 \x01(\x0b\x32\x1a.perception.Tsr.TsrWarning\x12(\n\x0b\x64\x61ta_source\x18\x05 \x01(\x0e\x32\x13.minieye.DataSource\x1a\xea\x01\n\x0bTsrTraceRes\x12+\n\x08\x64\x65t_rect\x18\x01 \x01(\x0b\x32\x19.perception.common.Rect2f\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08hit_type\x18\x03 \x01(\x05\x12\x11\n\ttsr_class\x18\x04 \x01(\x05\x12\x11\n\ttsr_value\x18\x05 \x01(\x05\x12\x0e\n\x06tsr_id\x18\x06 \x01(\x05\x12\x11\n\ttrack_cnt\x18\x07 \x01(\x05\x12\x19\n\x11longitudinal_dist\x18\x08 \x01(\x02\x12\x14\n\x0clateral_dist\x18\t \x01(\x02\x12\x0e\n\x06height\x18\n \x01(\x02\x1ah\n\nTsrWarning\x12\x14\n\x0cheight_limit\x18\x01 \x01(\x02\x12\x14\n\x0cweight_limit\x18\x02 \x01(\x02\x12\x13\n\x0bspeed_limit\x18\x03 \x01(\x05\x12\x19\n\x11tsr_warning_level\x18\x04 \x01(\x05\x62\x06proto3')



_TSR = DESCRIPTOR.message_types_by_name['Tsr']
_TSR_TSRTRACERES = _TSR.nested_types_by_name['TsrTraceRes']
_TSR_TSRWARNING = _TSR.nested_types_by_name['TsrWarning']
Tsr = _reflection.GeneratedProtocolMessageType('Tsr', (_message.Message,), {

  'TsrTraceRes' : _reflection.GeneratedProtocolMessageType('TsrTraceRes', (_message.Message,), {
    'DESCRIPTOR' : _TSR_TSRTRACERES,
    '__module__' : 'tsr_pb2'
    # @@protoc_insertion_point(class_scope:perception.Tsr.TsrTraceRes)
    })
  ,

  'TsrWarning' : _reflection.GeneratedProtocolMessageType('TsrWarning', (_message.Message,), {
    'DESCRIPTOR' : _TSR_TSRWARNING,
    '__module__' : 'tsr_pb2'
    # @@protoc_insertion_point(class_scope:perception.Tsr.TsrWarning)
    })
  ,
  'DESCRIPTOR' : _TSR,
  '__module__' : 'tsr_pb2'
  # @@protoc_insertion_point(class_scope:perception.Tsr)
  })
_sym_db.RegisterMessage(Tsr)
_sym_db.RegisterMessage(Tsr.TsrTraceRes)
_sym_db.RegisterMessage(Tsr.TsrWarning)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TSR._serialized_start=61
  _TSR._serialized_end=584
  _TSR_TSRTRACERES._serialized_start=244
  _TSR_TSRTRACERES._serialized_end=478
  _TSR_TSRWARNING._serialized_start=480
  _TSR_TSRWARNING._serialized_end=584
# @@protoc_insertion_point(module_scope)
