const ConvertMap = {
  'vehicle':[
    [
      'frame_id',
      'bumper_warning',
      'headway_warning',
      'stop_and_go_warning',
      'forward_collision_warning' ,
      'warning_level',
      'warning_vehicle_index',
      'speed',
      'radius',
      'light_mode',
      'focus_index',
      'ttc'
    ],
    [
      'dets',
      'type',
      'warning_level',
      'vertical_dist',
      'horizontal_dist',
      'ttc',
      'index',
      'bounding_rect',
    ]
  ],
  'lane':[
    [
      'frame_id',
      'speed',
      'lateral_speed',
      'speed_thresh',
      'left_lamp',
      'right_lamp',
      'deviate_trend',
      'turn_radius'
    ],
    [
      'lanelines',
      'warning',
      'type',
      'start',
      'end',
      'color',
      'width',
      'label',
      'perspective_view_poly_coeff', 
      'bird_view_poly_coeff'
    ]
  ],
  'pcw':[
    [
      'frame_id',
      'pcw_on',
      'ped_on'
    ],
    [
      'pedestrians',
      'roi_num',
      'classify_type',
      'dist',
      'ttc',
      'is_key',
      'is_danger',
      'world_x',
      'world_y',
      'regressed_box',
    ]
  ],
  'tsr':[
    [
      'frame_id',
      'tsr_warning_level',
      'focus_index',
      'speed_limit'
    ],
    [
      'dets',
      'index',
      'position',
      'max_speed'
    ]
  ],
}

module.exports = {
  ConvertMap
}