
== nanomsg
* 图片和算法结果通过nanomsg接收
* 通过nanomsg的socket连接到设备指定端口接收数据：tcp://<设备ip>:<端口号>
* 其中端口对应关系为：
** 图片：1200， lane(车道线):1203, tsr(交通牌):1206，vehicle(车辆):1204, ped(行人):1205
* 图片数据格式
** 图片尺寸：720 x 1280
** 图像帧id: byte4-byte8
** 图像数据： 彩色图像为3通道rgb格式，从 byte24 起
* 算法数据格式
** 算法数据为经过msgpack打包的json对象
** 字段说明参考 ADAS算法检测结果字段说明.pdf
* 示例：
[source, python]
'''
依赖：
    python3.5
    源码编译安装nanomsg, https://github.com/nanomsg/nanomsg
    pip: msgpack==0.5.6, nanomsg==1.0, opencv-python==3.4.3.18
'''
def recv_msg(ip, port):
    #nanomsg接收消息
    socket = nanomsg.wrapper.nn_socket(nanomsg.AF_SP, nanomsg.SUB)
    nanomsg.wrapper.nn_setsockopt(socket, nanomsg.SUB, nanomsg.SUB_SUBSCRIBE, "")
    nanomsg.wrapper.nn_connect(socket, "tcp://%s:%s" % (ip, port, ))
    while True:
        buf = nanomsg.wrapper.nn_recv(socket, 0)
        msg = buf[1]
#
def parse_image(msg):
    #解析图像数据
    msg = memoryview(msg).tobytes()
    frame_id = int.from_bytes(msg[4:8], byteorder="little", signed=False)
    data = msg[24:]
    image = cv2.imdecode(np.fromstring(data, np.uint8), cv2.IMREAD_COLOR)
    return frame_id, image
#
def parse_algo(msg):
    #解析算法结果数据
    data = msgpack.loads(msg)
    res = convert(data)
    frame_id = res['frame_id']
    return frame_id, res
#
def convert(data):
    #msgpack解压nanomsg的数据后所有字符串都是bytes类型，转成str类型
    if isinstance(data, bytes):      return data.decode('ascii')
    if isinstance(data, dict):       return dict(map(convert, data.items()))
    if isinstance(data, tuple):      return tuple(map(convert, data))
    if isinstance(data, list):       return list(map(convert, data))
    if isinstance(data, set):        return set(map(convert, data))
    return data